### ISSUE TITLE
Tag visibility in blog posts?

### ISSUE THREAD

**Issue by jenren** [nanxstats/hugo-renga#1]
Hi Nan! First off, thanks so much for building and sharing this template; I really like the style and I'm using it to rewrite my own personal website in blogdown.

As I'm doing so, I noticed that the ability to view a post's tags (specified via a post's `tags` field) after the "X minute read" seems to be available based on your screenshot here:

![image](https://user-images.githubusercontent.com/5131960/53303650-f2cb5980-3821-11e9-8903-b9425052a6dc.png)

However, it looks like your live demo website, personal website, and my versions don't allow for it. I'm new to building websites and can't seem to figure out how to enable tags -- where could I start, or is this something not allowed anymore in your Renga template?

**Comment by nanxstats** [comment]
Hi Jen,

-thanks for using the theme. It does support displaying tags indeed. I'm not sure why it didn't work for you, but I guess the posts should be written in R Markdown (`.Rmd`) with tags in the header section, for example:

https://github.com/road2stat/nanx.me/blob/master/content/blog/post/2018-05-21-shiny-async.Rmd
https://nanx.me/blog/post/shiny-async/

**Comment by jenren** [comment]
Hi Nan, thanks for the quick response! It works now; also not sure why it wasn't working before. Appreciate your help.
