### ISSUE TITLE
Issue in the layouts

### ISSUE THREAD

**Issue by tejendrapsingh** [nanxstats/hugo-renga#10]
Hey!

I am trying to push the modifications to the github but keep running into this error.
Not sure why this is happening.

`The value '{}' was passed to a date-related filter that expects valid dates in /_layouts/default.html or one of its layouts.`

My repository is [here](https://github.com/tejendrapsingh/tejendrapsingh.github.io).

Any help is greatly appreciated.

**Comment by nanxstats** [comment]
https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
