### ISSUE TITLE
Migrate from UA to GA4

### ISSUE THREAD

**Issue by AntoineSoetewey** [nanxstats/hugo-renga#12]
Dear Nan,

Universal Analytics will no longer process new data in standard properties beginning July 1, 2023.

Therefore, I created a GA4 tag and inserted it in my config.toml (as you can see [here](https://github.com/AntoineSoetewey/statsandr/blob/master/config.toml#L13)). However, it doesn't seem to work since there is no data on my GA dashboard.

Is there anything else I need to do to switch from UA to GA4?

Thanks in advance for your help!

**Comment by AntoineSoetewey** [comment]
Never mind, I fixed it!

Based on this [tutorial](https://gohugo.io/templates/internal/) from Hugo, I edited this [line](https://github.com/AntoineSoetewey/statsandr/blob/master/themes/hugo-renga/layouts/_default/baseof.html#L80) in the baseof.html file.

**Comment by nanxstats** [comment]
Nice! Thanks for the note.
