### ISSUE TITLE
Dark theme?

### ISSUE THREAD

**Issue by AntoineSoetewey** [nanxstats/hugo-renga#8]
Dear Nan,

I would like to implement the possibility to switch between light and dark mode on my blog (which uses your theme), as shown here: https://christianoliff.com/blog/dark-mode-theme-switch.

By any chance, do you expect to implement this feature?

Regards,
Antoine

**Comment by nanxstats** [comment]
Hey @AntoineSoetewey I don't any plans of doing that. Please feel free to fork the theme and make it happen on your side.

**Comment by AntoineSoetewey** [comment]
Thanks for your answer!
