### ISSUE TITLE
Logo image not showing up on mobile

### ISSUE THREAD

**Issue by dhersz** [nanxstats/hugo-renga#9]
Hi. First, thanks for the theme, I'm really enjoying using it.

I noticed that the logo image is not showing up on my website when accessed via mobile. In fact, the same is true for your personal website (https://nanx.me/). Is this intended? If so, is there a way to "bypass" such feature?

Thank you again! Cheers

**Comment by nanxstats** [comment]
@dhersz Yes, it's intended. You can use the `d-none` property to turn it on/off:

https://github.com/nanxstats/hugo-renga/blob/master/layouts/partials/header.html#L4

https://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements

**Comment by dhersz** [comment]
That did the trick! Thank you very much
